language: python
python:
  - "2.7"
cache:
  - pip: true
  - apt: true
  - custom_install: true
sudo: required
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - gfortran
      - libblas-dev
      - liblapack-dev
before_install:
    - pip install coveralls
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib basemap netcdf4
script: ./testall
after_success:
  - coveralls
