language: python

python:
  - 2.7
  - 3.6

services:
  - docker

matrix:
  fast_finish: true

before_install:
  - if [ $TRAVIS_PYTHON_VERSION == 2.7 ]; then
      export DOCKERFILE="Dockerfile.oil.py2" CACHE_FROM="opendrift/opendrift-oil:latest";
    else
      export DOCKERFILE="Dockerfile"         CACHE_FROM="opendrift/opendrift:latest";
    fi

install:
  - pip install pyyaml coveralls
  - cd docker
  - docker build --pull --cache-from ${CACHE_FROM} -t opendrift:${TRAVIS_COMMIT} --file ${DOCKERFILE} ..
  - cd ..

script:
  - docker run -itd --name="opendrift_${TRAVIS_COMMIT}" opendrift:${TRAVIS_COMMIT}
  - docker exec "opendrift_${TRAVIS_COMMIT}" bash -c ". ~/.bashrc && pytest --cov=opendrift --ignore=tests/benchmarks --ignore=tests/wps"

after_success:
  - docker cp "opendrift_${TRAVIS_COMMIT}":/code/.coverage .
  - docker stop "opendrift_${TRAVIS_COMMIT}"
  - cat .coverage
  - sed -e "s|\/code\/|${PWD}\/|g" -i .coverage
  # - coverage combine
  - cat .coverage
  - coveralls
