language: python
python:
  - "2.7"
sudo: required
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib basemap netcdf4
    - conda install -c hargup python-coveralls
script: ./testall
after_success:
  - coveralls
