language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=1.7   SCIPY_VERSION=0.11 NETCDF_VERSION=1
  - NUMPY_VERSION=1.11  SCIPY_VERSION=0.17 NETCDF_VERSION=1.2
  - NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1 NETCDF_VERSION=1 # Hexagon
  - NUMPY_VERSION=1.11.1 SCIPY_VERSION=0.18.0 NETCDF_VERSION=1.2.4 # Marta
matrix:
  allow_failures:
    - env: NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1 NETCDF_VERSION=1
cache:
  directories:
    - $HOME/download
    - $HOME/miniconda2
    - $HOME/oillibrary
sudo: required
before_install:
  - if [[ ! -e $HOME/miniconda2/bin ]]; then
        mkdir -p download;
        cd download;
        wget -c http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b -f;
        cd ..;
    fi
  - export PATH=/home/travis/miniconda2/bin:$PATH
  #- conda update --yes conda
  - if [[ ! -e $HOME/oillibrary ]]; then
        mkdir -p oillibrary;
        cd oillibrary;
        git clone https://github.com/NOAA-ORR-ERD/OilLibrary.git;
        cd OilLibrary;
        #pip install -r requirements.txt;
        python setup.py develop;
        cd ../..;
    fi
  - export PYTHONPATH=$PYTHONPATH:$HOME/oillibrary/OilLibrary
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib basemap=1.0.7 netcdf4=$NETCDF_VERSION configobj
  - conda install --yes -c dan_blanchard python-coveralls
  - pip install SQLAlchemy
  - pip install zope.sqlalchemy
  - pip install awesome-slugify
  - pip install repoze.lru
  - pip install "git+https://github.com/NOAA-ORR-ERD/PyNUCOS.git#egg=unit_conversion"
script: coverage run --source=opendrift setup.py test
after_success:
  - coveralls
