language: python
addons:
  apt:
    packages:
    - gfortran
python:
  - 2.7
  - 3.5
env:
  - NUMPY=1.7    SCIPY=0.11   NETCDF=1.0   MATPLOTLIB=1.3
  - NUMPY=1.8.2  SCIPY=0.13.3 NETCDF=1.1   MATPLOTLIB=1.3 # Ubuntu 14.04
  - NUMPY=1.9    SCIPY=0.17   NETCDF=1.1   MATPLOTLIB=1.4
  - NUMPY=1.10   SCIPY=0.17   NETCDF=1.2.1 MATPLOTLIB=1.4
  - NUMPY=1.11   SCIPY=0.17   NETCDF=1.2.4 MATPLOTLIB=1.5
  - NUMPY=1.12   SCIPY=0.19.0 NETCDF=1.2.7 MATPLOTLIB=1.5
  - NUMPY=1.13   SCIPY=0.19   NETCDF=1.2.4 MATPLOTLIB=2.0
  - NUMPY=1.13.3 SCIPY=1.0    NETCDF=1.3.0 MATPLOTLIB=2.0 # Bleeding edge
matrix:
  fast_finish: true
  allow_failures:
    - env: NUMPY=1.7    SCIPY=0.11   NETCDF=1.0   MATPLOTLIB=1.3
    - env: NUMPY=1.8.2  SCIPY=0.13.3 NETCDF=1.1   MATPLOTLIB=1.3
    - env: NUMPY=1.12   SCIPY=0.19.0 NETCDF=1.2.7 MATPLOTLIB=1.5
cache:
  directories:
    - $HOME/download2
    - $HOME/download3
    - $HOME/miniconda2
    - $HOME/miniconda3
sudo: required
before_install:
  - if [ $TRAVIS_PYTHON_VERSION == 2.7 ]; then
        condaURL=https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh;
        condabin=$HOME/miniconda2/bin;
        condapath=/home/travis/miniconda2/bin:$PATH;    
        download=/$HOME/download2;
    elif [ $TRAVIS_PYTHON_VERSION == 3.5 ]; then
        condaURL=https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh;
        condabin=$HOME/miniconda3/bin;
        condapath=/home/travis/miniconda3/bin:$PATH;    
        download=/$HOME/download3;
    fi
  - if [ ! -e $condabin ]; then
        sudo apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev;
        mkdir -p $download;
        cd $download;
        wget -c $condaURL -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b -f;
        cd ..;
    fi
  - export PATH=$condapath
  - export PYTHONPATH=$PYTHONPATH:$HOME/oillibrary/OilLibrary
install:
  - conda install --yes hdf4 python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY scipy=$SCIPY matplotlib=$MATPLOTLIB basemap=1.0.7 netcdf4=$NETCDF configobj
  - conda config --add channels conda-forge
  - conda install -c conda-forge coveralls 
  - if [ ! -e $HOME/oillibrary ] && [ $TRAVIS_PYTHON_VERSION == 2.7 ]; then
        cd $HOME;
        mkdir -p oillibrary;
        cd oillibrary;
        git clone https://github.com/NOAA-ORR-ERD/OilLibrary.git;
        cd OilLibrary;
        pip install -r requirements.txt;
        python setup.py develop --user;
    fi
  - conda install --yes hdf4 python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY scipy=$SCIPY matplotlib=$MATPLOTLIB basemap=1.0.7 netcdf4=$NETCDF configobj
  - cd /home/travis/build/OpenDrift/opendrift
script: coverage run --source=opendrift setup.py test
after_success:
  - coveralls
