language: python
python:
  - "2.7"
sudo: required
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - gfortran
      - libblas-dev
      - liblapack-dev
install:
  - travis_wait 40 pip install -r requirements.txt
  - sudo ls -l /usr/lib/
  - sudo ln -s /usr/lib/libgeos-3.3.8.so /usr/lib/libgeos.so
  - pip install https://github.com/matplotlib/basemap/archive/v1.0.7rel.tar.gz --allow-external basemap --allow-unverified basemap
script: ./testall
