language: python
python:
  - "2.7"
env:
  global:
    - BASEMAP_VERSION=1.0.7
  matrix:
    - NUMPY_VERSION=1.7   SCIPY_VERSION=0.11
    - NUMPY_VERSION=1.7   SCIPY_VERSION=0.17
    - NUMPY_VERSION=1.11  SCIPY_VERSION=0.11
    - NUMPY_VERSION=1.11  SCIPY_VERSION=0.17
    - NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1  # Hexagon
cache:
  directories:
    - $HOME/download
    - $HOME/miniconda2
sudo: required
before_install:
  - ls -al $HOME
  - ls -al $HOME/download
  - ls -al $HOME/miniconda2
  - if [[ ! -e $HOME/miniconda2/bin ]]; then
        mkdir -p download;
        cd download;
        wget -c http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b -f;
        cd ..;
    fi
  - export PATH=/home/travis/miniconda2/bin:$PATH
  #- conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib basemap=$BASEMAP_VERSION netcdf4 configobj
  - conda install --yes -c dan_blanchard python-coveralls
script: coverage run --source=opendrift setup.py test
after_success:
  - coveralls
