language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=1.7   SCIPY_VERSION=0.11 NETCDF_VERSION=1 MATPLOTLIB_VERSION=1.3
  - NUMPY_VERSION=1.9   SCIPY_VERSION=0.17 NETCDF_VERSION=1 MATPLOTLIB_VERSION=1.4
  - NUMPY_VERSION=1.9.3   SCIPY_VERSION=0.17 NETCDF_VERSION=1 MATPLOTLIB_VERSION=1.4
  - NUMPY_VERSION=1.10   SCIPY_VERSION=0.17 NETCDF_VERSION=1 MATPLOTLIB_VERSION=1.4
  - NUMPY_VERSION=1.11  SCIPY_VERSION=0.17 NETCDF_VERSION=1 MATPLOTLIB_VERSION=1.5
  - NUMPY_VERSION=1.11  SCIPY_VERSION=0.17 NETCDF_VERSION=1.2 MATPLOTLIB_VERSION=1.5
  - NUMPY_VERSION=1.13  SCIPY_VERSION=0.19 NETCDF_VERSION=1.2.4 MATPLOTLIB_VERSION=2.0 # Bleeding edge
  - NUMPY_VERSION=1.12.0 SCIPY_VERSION=0.15.1 NETCDF_VERSION=1.2.7 MATPLOTLIB_VERSION=1.4.3 # Hexagon
  - NUMPY_VERSION=1.11.1 SCIPY_VERSION=0.18.0 NETCDF_VERSION=1.2.4 MATPLOTLIB_VERSION=1.5 # Marta
matrix:
  allow_failures:
    - env: NUMPY_VERSION=1.12.0 SCIPY_VERSION=0.15.1 NETCDF_VERSION=1.2.7 MATPLOTLIB_VERSION=1.4.3
    - env: NUMPY_VERSION=1.7   SCIPY_VERSION=0.11 NETCDF_VERSION=1 MATPLOTLIB_VERSION=1.3
    - env: NUMPY_VERSION=1.9   SCIPY_VERSION=0.17 NETCDF_VERSION=1 MATPLOTLIB_VERSION=1.4
    - env: NUMPY_VERSION=1.9.3   SCIPY_VERSION=0.17 NETCDF_VERSION=1 MATPLOTLIB_VERSION=1.4
cache:
  directories:
    - $HOME/download
    - $HOME/miniconda2
sudo: required
before_install:
  - sudo apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev
  - if [[ ! -e $HOME/miniconda2/bin ]]; then
        mkdir -p download;
        cd download;
        #wget -c https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        wget -c https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b -f;
        cd ..;
    fi
  - export PATH=/home/travis/miniconda2/bin:$PATH
#  - conda update --yes conda
  - export PYTHONPATH=$PYTHONPATH:$HOME/oillibrary/OilLibrary
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda install --yes hdf4 python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib=$MATPLOTLIB_VERSION basemap=1.0.7 netcdf4=$NETCDF_VERSION configobj
  - if [[ ! -e $HOME/oillibrary ]]; then
        cd $HOME;
        mkdir -p oillibrary;
        cd oillibrary;
        git clone https://github.com/NOAA-ORR-ERD/OilLibrary.git;
        cd OilLibrary;
        sudo -H pip install -r requirements.txt;
        sudo python setup.py develop;
    fi
  - conda install --yes -c dan_blanchard python-coveralls
  - cd /home/travis/build/OpenDrift/opendrift
script: coverage run --source=opendrift setup.py test
after_success:
  - coveralls
